Add functional tests and test setup
ElementareTeilchen/unduplicator pull request #9
Opened 2023-05-06 10:10 UTC by sypets

This patch is based on PR #3. It includes the commits of that PR and adds functional tests, test setup and GitHub CI in additional commits.

PR #3 should be merged first, then this PR can be rebased and merged.

A typical setup using runTests.sh is used as explained in the official documentation: https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/Testing/ExtensionTesting.html (this is slightly outdated but is being updated as we speak).

with 

* a GitHub CI file in .github/workflows/ci.yml to run the tests automatically in the future for each PR
* .attributes file so that the Tests are not packaged when installing the extension
* .gitignore so that the build files (.Build, composer.lock etc.) are not included in this repo
* runTests.sh & friends in Build directory
* functional tests in Tests/Functional which check if the fix in PR #3 works and some more basic testing

To execute the functional tests locally:

```
Build/Scripts/runTests.sh -s composerInstallMax -p 8.1
Build/Scripts/runTests.sh -s functional -p 8.1
```

The build can be removed with
```
rm -rf .Build
rm composer.lock

```

To not bloat up this PR too much, extra checks were not added, but are recommended:

* setup php-cgl-fixer and .editorconfig for coding guidelines with [typo3/coding-standards](https://packagist.org/packages/typo3/coding-standards)
* unit test. For this, the xml and boostrap file must be added to Build/phpunit (from typo3/testing-framework)
* run `composer validate`
* run lint
* install `phpstan` and execute checks
* add CONTRIBTING.md with info how to execute the checks and tests locally

2023-05-06 17:01 UTC, sbuerk requested changes

2023-05-06 18:21 UTC, sypets commented on Build/Scripts/runTests.sh
> +    -t <composer-core-version-constraint>
-t is currently not used. I removed / commented out the commands which are not used or not fully supported right now. Configuration files for phpstan and php-cs-fixer are also not supplied yet. Can be done with followup patch.

2023-05-06 18:21 UTC, sypets commented on Build/Scripts/cleanup.sh
> +#!/bin/bash
Added -s cleanBuild

2023-05-06 18:22 UTC, sypets commented on Build/Scripts/cleanup.sh
> +rm -rf .Build
Done.

> When removing composer.lock, removing the vendor folder would make sense I guess.

The vendor folder is in .Build and that is already removed.

2023-05-06 18:22 UTC, sypets commented on Build/Scripts/runTests.sh
> +            - cglGit: test and fix latest committed patch for CGL compliance
Done. Commented out.

2023-05-06 18:22 UTC, sypets commented on Build/testing-docker/docker-compose.yml
> +          --config=Build/.php-cs-fixer.php .
dito.

2023-05-06 18:23 UTC, sypets commented
@sbuerk Thank you for review! Should all be fixed now.

2023-05-08 06:52 UTC, merged

2023-05-08 09:01 UTC, franzkugelmann commented
Thanks @sypets and @sbuerk! Beware, i renamed the branch master to main. Looking forward to further collaboration on the unduplicator.